# Generated by Django 4.2.10 on 2026-01-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_limit',
        ),
    ]
