# Generated by Django 4.2.10 on 2026-01-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_organizer_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='principal_g_status_089cd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='principal_g_organiz_d2a4c7_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='has_powerball',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_numbers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_numbers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_draw',
        ),
        migrations.RemoveField(
            model_name='game',
            name='powerball_range',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ticket_sale_end',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='principal_g_status_886099_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['company'], name='principal_g_company_42d271_idx'),
        ),
    ]
