# Generated by Django 4.2.10 on 2026-01-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefinance',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
