# Generated by Django 4.2.10 on 2026-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_gamefinance_settled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_draw',
            field=models.DateTimeField(blank=True, help_text='The date and time when the draw will take place', null=True, verbose_name='Next Draw Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage taken by platform from ticket sales', max_digits=5, verbose_name='Platform Commission (%)'),
        ),
    ]
