# Generated by Django 4.2.10 on 2026-02-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_game_next_draw_alter_game_platform_fee_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='winning_powerball',
        ),
        migrations.RemoveField(
            model_name='syndicate',
            name='powerball',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='has_powerball_match',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='powerball',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='prize_tier',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='prize_tier',
        ),
    ]
